import OverwatchData
HeroList = ["Lucio","Reinhardt","McCree","Mercy","Zarya","DVa","Genji","Junkrat","Pharah","Reaper","Roadhog","Soldier 76","Symmetra","Widowmaker","Winston","Hanzo","Mei","Tracer","Bastion","Torbjorn","Zenyatta","Ana","Sombra","Orisa","Doomfist","Moira","Brigitte","Hammond","Ashe","Baptiste","Sigma"]

OverwatchInfo = [
  OverwatchData.Lucio.LuicoInfo,OverwatchData.Reinhardt.ReinhardtInfo,OverwatchData.McCree.McCreeInfo,OverwatchData.Mercy.MercyInfo,OverwatchData.Zarya.ZaryaInfo,OverwatchData.DVa.DVaInfo,OverwatchData.Genji.GenjiInfo,OverwatchData.Junkrat.JunkratInfo,OverwatchData.Pharah.PharahInfo,OverwatchData.Reaper.ReaperInfo,OverwatchData.Roadhog.RoadhogInfo,OverwatchData.Soldier76.Soldier76Info,OverwatchData.Symmetra.SymmetraInfo,OverwatchData.Widowmaker.WidowmakerInfo,OverwatchData.Winston.WinstonInfo,OverwatchData.Hanzo.HanzoInfo,OverwatchData.Mei.MeiInfo,OverwatchData.Tracer.TracerInfo,OverwatchData.Bastion.BastionInfo,OverwatchData.Torbjorn.TorbjornInfo,OverwatchData.Zenyatta.ZenyattaInfo,OverwatchData.Ana.AnaInfo,OverwatchData.Sombra.SombraInfo,OverwatchData.Orisa.OrisaInfo,OverwatchData.Doomfist.DoomfistInfo,OverwatchData.Moira.MoiraInfo,OverwatchData.Brigitte.BrigitteInfo,OverwatchData.Hammond.HammondInfo,OverwatchData.Ashe.AsheInfo,OverwatchData.Baptiste.BaptisteInfo,OverwatchData.Sigma.SigmaInfo]
OverwatchCounters = [
  OverwatchData.Lucio.LucioCounters,OverwatchData.Reinhardt.ReinhardtCounters,OverwatchData.McCree.McCreeCounters,OverwatchData.Mercy.MercyCounters,OverwatchData.Zarya.ZaryaCounters,OverwatchData.DVa.DVaCounters,OverwatchData.Genji.GenjiCounters,OverwatchData.Junkrat.JunkratCounters,OverwatchData.Symmetra.SymmetraCounters,OverwatchData.Widowmaker.WidowmakerCounters,OverwatchData.Winston.WinstonCounters,OverwatchData.Hanzo.HanzoCounters,OverwatchData.Mei.MeiCounters,OverwatchData.Tracer.TracerCounters,OverwatchData.Bastion.BastionCounters,OverwatchData.Torbjorn.TorbjornCounters,OverwatchData.Zenyatta.ZenyattaCounters,OverwatchData.Ana.AnaCounters,OverwatchData.Sombra.SombraCounters,OverwatchData.Orisa.OrisaCounters,OverwatchData.Doomfist.DoomfistCounters,OverwatchData.Moira.MoiraCounters,OverwatchData.Brigitte.BrigitteCounters,OverwatchData.Hammond.HammondCounters,OverwatchData.Ashe.AsheCounters,OverwatchData.Baptiste.BaptisteCounters,OverwatchData.Sigma.SigmaCounters]
OverwatchSynergies = [
  OverwatchData.Lucio.LucioSynergies,OverwatchData.Reinhardt.ReinhardtSynergies,OverwatchData.McCree.McCreeSynergies,OverwatchData.Mercy.MercySynergies,OverwatchData.Zarya.ZaryaSynergies,OverwatchData.DVa.DVaSynergies,OverwatchData.Genji.GenjiSynergies,OverwatchData.Junkrat.JunkratSynergies,OverwatchData.Symmetra.SymmetraSynergies,OverwatchData.Widowmaker.WidowmakerSynergies,OverwatchData.Winston.WinstonSynergies,OverwatchData.Hanzo.HanzoSynergies,OverwatchData.Mei.MeiSynergies,OverwatchData.Tracer.TracerSynergies,OverwatchData.Bastion.BastionSynergies,OverwatchData.Torbjorn.TorbjornSynergies,OverwatchData.Zenyatta.ZenyattaSynergies,OverwatchData.Ana.AnaSynergies,OverwatchData.Sombra.SombraSynergies,OverwatchData.Orisa.OrisaSynergies,OverwatchData.Doomfist.DoomfistSynergies,OverwatchData.Moira.MoiraSynergies,OverwatchData.Brigitte.BrigitteSynergies,OverwatchData.Hammond.HammondSynergies,OverwatchData.Ashe.AsheSynergies,OverwatchData.Baptiste.BaptisteSynergies,OverwatchData.Sigma.SigmaSynergies]
array_length = len(HeroList)
ListHeroes = []
ListCounters = []
ListSynergies = []
ListOfListCounters = []

